dist: trusty
language: generic

git:
  depth: 1

sudo: required
  
script:
  - bash ./remaster.sh |& tee log.txt
  - sudo rm -f *original.iso

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh *.iso*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
