dist: trusty
language: generic

git:
  depth: 1

sudo: required
  
script:
  - ./build1.sh |& tee log.txt
 
before_deploy:
  - sudo rm -f meilix-original.iso
  - export image_name="`echo *.iso`"
  - cat *.iso > "/home/travis/${image_name}"
